version: '3.5'

services:
  mosquitto:
    container_name: mosquitto_container_v2
    image: eclipse-mosquitto:2.0.18
    volumes:
      - ./config:/mosquitto/config/
      - ./config/passwd:/mosquitto/config/passwd
      - ./logs:/mosquitto/logs/
    ports:
      - '1883:1883'
      - '9001:9001'
    networks:
      - default
    restart: unless-stopped

networks:
  default:
